version: '3.8'

services:
  # --- SERVIDOR WEB ---
  app:
    build: ./docker
    container_name: nexstore_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: nexstore_db
      DB_USER: nex_user
      DB_PASSWORD: nex_password
    depends_on:
      - db
    networks:
      - nexstore-red

  # --- BASE DE DATOS ---
  db:
    image: mysql:8.0
    container_name: nexstore_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nexstore_db
      MYSQL_USER: nex_user
      MYSQL_PASSWORD: nex_password
    volumes:
      - nexstore_datos:/var/lib/mysql
    networks:
      - nexstore-red

  # --- GESTOR VISUAL (phpMyAdmin) ---
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: nexstore_pma
    environment:
      PMA_HOST: db
      PMA_USER: nex_user
      PMA_PASSWORD: nex_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - nexstore-red

volumes:
  nexstore_datos:

networks:
  nexstore-red:
    driver: bridge